# Generated by Django 2.2.3 on 2021-11-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_order_saleguide'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_standard',
            field=models.BooleanField(default=False),
        ),
    ]
