# Generated by Django 2.2.3 on 2021-11-06 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0006_auto_20211106_0523'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCatgories',
            new_name='ProductCategories',
        ),
    ]
