# Generated by Django 2.2.3 on 2021-11-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0008_auto_20211111_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.IntegerField(null=True),
        ),
    ]
