# Generated by Django 2.2.3 on 2021-11-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0009_auto_20211111_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('can_make_orders', 'Can make orders'), ('can_mark_orders_as_ready', 'Can mark orders as ready'), ('can_mark_orders_as_served', 'Can mark orders as served')]},
        ),
    ]
