# Generated by Django 2.2.3 on 2021-11-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0011_auto_20211112_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
