# Generated by Django 2.2.3 on 2021-11-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0012_auto_20211112_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
