# Generated by Django 2.2.3 on 2021-11-18 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0014_auto_20211117_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.OrderGroup'),
        ),
    ]
