# Generated by Django 2.2.3 on 2021-11-19 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bar', '0015_auto_20211118_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cashier',
        ),
        migrations.RemoveField(
            model_name='order',
            name='waiter',
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='cashier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='waiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiter', to=settings.AUTH_USER_MODEL),
        ),
    ]
