# Generated by Django 2.2.3 on 2021-12-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0017_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_limit',
            field=models.FloatField(default=0),
        ),
    ]
