# Generated by Django 2.2.3 on 2021-12-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0018_product_stock_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'PENDING'), (1, 'READY'), (2, 'PAID')], default=2),
        ),
    ]
