# Generated by Django 2.2.3 on 2021-12-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0019_ordergroup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='customer',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
