# Generated by Django 2.2.3 on 2021-12-08 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0022_auto_20211205_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='metric_system',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bar.MetricSystem'),
            preserve_default=False,
        ),
    ]
